apiVersion: v1
kind: Service
metadata:
  name: meshcentral
  labels:
    app: meshcentral
spec:
  selector:
    app: meshcentral
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
